version: '3'

services:
  api:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: ./dockerfile.api
    ports:
      - "3000:3000"
    depends_on:
      - db    
  db:
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    build:
      context: .
      dockerfile: ./dockerfile.db
    ports:
      - "5432:5432"