FROM node:20-alpine

ARG API_COMMAND
ENV API_COMMAND ${API_COMMAND:-dev}

WORKDIR /

COPY api/package*.json ./

COPY packages/schema ./packages/schema

RUN npm install file:./packages/schema

COPY ./api ./

EXPOSE 3000

CMD ["sh", "-c", "npm run $API_COMMAND"]