version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: ./dockerfile.api
    ports:
      - "3000:3000"
    depends_on:
      - db    
  db:
    build:
      context: .
      dockerfile: ./dockerfile.db
    ports:
      - "5432:5432"